name: rl-chess
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - numpy
  - pip
  - pytorch
  - torchvision
  - cudatoolkit=11.8  # Optional, for GPU support (adjust or remove if not needed)
  - pip:
      - python-chess
